//
//  NewsAPI.swift
//  getting-news
//
//  Created by MIkkyMouse on 12.09.2020.
//  Copyright (c) 2020 Ivan Sosnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

//https://newsapi.org/v2/top-headlines?country=ru&apiKey=ВашApiKey
struct NewsApi {
    
    
    
    static let scheme = "https"
    static let host = "newsapi.org"
    static let path = "/v2/top-headlines"
    
    static func returnParametrs(for page: Int) -> [String: String] {
        let parametrs = [
            "country" : "ru",
            "apiKey" : "6a2721412db340b085738481f210244a",
            "page" : "\(page)"
        ]
        return parametrs
    }
    
    
}
