//
//  NewsResponse.swift
//  getting-news
//
//  Created by MIkkyMouse on 12.09.2020.
//  Copyright (c) 2020 Ivan Sosnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct NewsResponse: Codable {
}
