//
//  NewsRequest.swift
//  getting-news
//
//  Created by MIkkyMouse on 12.09.2020.
//  Copyright (c) 2020 Ivan Sosnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation


protocol NewsRequest: class {
   
}

class NetworkService: NewsRequest {
    
    static let shared = NetworkService()
    private init() {}
    
    func gettingStartNews(page: Int) {
        
        var components = URLComponents()
        
        components.scheme = NewsApi.scheme
        components.host = NewsApi.host
        components.path = NewsApi.path
        components.queryItems = NewsApi.returnParametrs(for: page).map({ URLQueryItem(name: $0, value: $1) })
        
        let session = URLSession.shared
        
        guard let url = components.url else { return }
        
        
        let task = session.dataTask(with: url) { (data , response, error) in
            
            guard let data = data else { return }
            DispatchQueue.main.async {
                let json = try? JSONSerialization.jsonObject(with: data, options: [])
                print(json)
            }
        }
        task.resume()
    }
    
}

